"""Executor node -- runs Aider against a target git repo.

Uses Aider's documented agentic workflow: --no-auto-commits + --no-dirty-commits
+ script-managed commits. Aider's auto-commit makes a SECOND LLM call to
generate the commit message, which hangs indefinitely on local models when the
target file has no prior git history. RALPH owns commit messages; Aider stays
a pure "code mutation engine".
See https://aider.chat/docs/scripting.html

Hardening: subprocess output streams live to ralph_run.log via a reader thread
so a hang is visible in real time. Hard timeout = AIDER_TIMEOUT. On timeout,
the subprocess is killed and we return TIMEOUT_SENTINEL in stderr so the
evaluator can score 0 and the loop can escalate.
"""
import os
import subprocess
import sys
import threading
import time
from pathlib import Path
from config import (
    OLLAMA_API_BASE, AIDER_TIMEOUT, GIT_TIMEOUT,
    SILENT_WARN_AFTER, TIMEOUT_SENTINEL,
)
from runlog import log, loud_timeout
from router import select_model
from state import RalphState


def _aider_cmd(task: str, model: str, repo_dir: Path) -> list[str]:
    # Pass both files so Aider can write implementation + test in one shot.
    # Aider creates files that don't exist yet when they're listed explicitly.
    solution = repo_dir / "solution.py"
    test_file = repo_dir / "test_solution.py"
    return [
        sys.executable, "-m", "aider",
        "--yes",
        "--no-auto-commits",
        "--no-dirty-commits",
        "--no-auto-lint",
        "--no-show-model-warnings",
        "--model", model,
        "--message", task,
        str(solution),
        str(test_file),
    ]


def _aider_env() -> dict:
    """Environment that prevents git from prompting for editor / credentials."""
    env = os.environ.copy()
    env["OLLAMA_API_BASE"]      = OLLAMA_API_BASE
    env["GIT_EDITOR"]           = "cmd /c exit 0"
    env["GIT_TERMINAL_PROMPT"]  = "0"
    # Force UTF-8 throughout the Aider subprocess — prevents cp1252 crashes on
    # Windows when Aider's Rich output contains block/box-drawing characters.
    env["PYTHONUTF8"]           = "1"
    env["PYTHONIOENCODING"]     = "utf-8"
    return env


def _git(repo_dir: Path, *args: str, env=None) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repo_dir), *args],
        capture_output=True, text=True, timeout=GIT_TIMEOUT,
        env=env or _aider_env(),
    )


def run_aider(task: str, model: str, repo_dir: Path) -> tuple[str, str]:
    """Run Aider, streaming output to ralph_run.log line-by-line.

    Returns (stdout, stderr). On timeout, stderr starts with TIMEOUT_SENTINEL
    so callers can route on it without parsing exceptions.
    """
    solution = repo_dir / "solution.py"
    if not solution.exists():
        solution.write_text("# generated by ralph\n", encoding="utf-8")

    cmd = _aider_cmd(task, model, repo_dir)
    log(f"aider -> model={model} timeout={AIDER_TIMEOUT}s files=solution.py+test_solution.py")

    proc = subprocess.Popen(
        cmd, cwd=str(repo_dir),
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, bufsize=1, env=_aider_env(),
    )

    captured: list[str] = []
    state = {"last_output": time.time(), "warned": False}

    def reader():
        try:
            for line in proc.stdout:
                state["last_output"] = time.time()
                captured.append(line)
                log(f"  aider | {line.rstrip()}", also_console=False)
        except Exception:
            pass

    rt = threading.Thread(target=reader, daemon=True)
    rt.start()

    deadline = time.time() + AIDER_TIMEOUT
    try:
        while proc.poll() is None:
            now = time.time()
            silence = now - state["last_output"]

            if not state["warned"] and silence >= SILENT_WARN_AFTER:
                state["warned"] = True
                log(f"  aider | WARN no output for {silence:.0f}s "
                    f"(hard timeout at {AIDER_TIMEOUT}s)")

            if now > deadline:
                loud_timeout(
                    f"aider model={model}", AIDER_TIMEOUT,
                    extra=f"silent for last {silence:.0f}s",
                )
                try: proc.kill()
                except Exception: pass
                rt.join(timeout=2)
                return "".join(captured), f"{TIMEOUT_SENTINEL} aider exceeded {AIDER_TIMEOUT}s"

            time.sleep(0.5)
    except KeyboardInterrupt:
        log("aider | KeyboardInterrupt — killing subprocess")
        try: proc.kill()
        except Exception: pass
        rt.join(timeout=2)
        raise

    rt.join(timeout=2)
    rc = proc.returncode
    log(f"aider <- finished rc={rc}")
    return "".join(captured), "" if rc == 0 else f"aider exit {rc}"


def commit_changes(repo_dir: Path, task: str, iteration: int) -> bool:
    """Commit any changes Aider made. Returns True if a commit was created."""
    status = _git(repo_dir, "status", "--porcelain")
    if not status.stdout.strip():
        return False
    _git(repo_dir, "add", "-A")
    msg = f"ralph iter {iteration}: {task[:70]}"
    r = _git(repo_dir, "commit", "-m", msg)
    return r.returncode == 0


def run_tests(repo_dir: Path) -> tuple[str, bool]:
    for cmd in (
        [sys.executable, "-m", "pytest", "--tb=short", "-q"],
        [sys.executable, "-m", "unittest", "discover", "-q"],
    ):
        result = subprocess.run(
            cmd, cwd=str(repo_dir),
            capture_output=True, text=True, timeout=60,
        )
        output = (result.stdout + result.stderr).strip()
        if output:
            return output, result.returncode == 0
    return "(no tests found)", False


def executor_node(state: RalphState) -> dict:
    model = select_model(state)
    repo_dir = Path(state["repo_dir"])
    iteration = state["iterations"] + 1
    task_prompt = f"{state['plan']}\n\nTask: {state['task']}"

    stdout, stderr = run_aider(task_prompt, model, repo_dir)

    timed_out = stderr.startswith(TIMEOUT_SENTINEL)

    if timed_out:
        log_entry = (f"[iter {iteration}] executor -> model={model} | TIMEOUT")
        return {
            "code": "",
            "test_output": TIMEOUT_SENTINEL,
            "model_used": model,
            "iterations": iteration,
            "timeout_count": state.get("timeout_count", 0) + 1,
            "log": state["log"] + [log_entry],
        }

    solution = repo_dir / "solution.py"
    code = solution.read_text(encoding="utf-8") if solution.exists() else ""
    edit_applied = "applied edit" in (stdout + stderr).lower()

    committed = commit_changes(repo_dir, state["task"], iteration) if edit_applied else False
    test_output, _ = run_tests(repo_dir)

    log_entry = (
        f"[iter {iteration}] executor -> model={model} | "
        f"{'edit applied' if edit_applied else 'no edit'}"
        f"{' | committed' if committed else ''}"
    )
    return {
        "code": code,
        "test_output": test_output,
        "model_used": model,
        "iterations": iteration,
        "timeout_count": 0,   # successful run resets the streak
        "log": state["log"] + [log_entry],
    }
