"""Executor node — writes code to the target repo.

Two code paths based on model type:

LOCAL (ollama/*):
  Call Ollama /api/chat directly. Extract code from ``` block. Write file.
  Local quantized models cannot reliably follow Aider's structured diff
  formats (SEARCH/REPLACE, udiff, whole) — they output whatever their
  training data shaped them to output. Direct API + code extraction is
  the only robust approach for this class of model.

CLOUD (gemini/*, gpt-*, claude-*, etc.):
  Use Aider with --edit-format diff. Cloud-scale models reliably follow
  structured diff formats and Aider's tooling (repo context, multi-file
  edits) adds real value at that scale.

Both paths write to solution.py and test_solution.py separately so the
model generates one file at a time (avoids context-length stalls).
"""
import json
import os
import re
import subprocess
import sys
import threading
import time
import urllib.request
from pathlib import Path

from config import (
    OLLAMA_API_BASE, AIDER_TIMEOUT, LOCAL_MODEL_TIMEOUT, GIT_TIMEOUT,
    SILENT_WARN_AFTER, TIMEOUT_SENTINEL, AIDER_LOG_PATH, ROOT
)
from runlog import log, loud_timeout, log_tool
from router import select_model
from state import RalphState
from hardware import get_free_vram_mb
from model_registry import calculate_safe_ctx, get_model_profile
from telemetry import tracer

def load_prompt(filename: str) -> str:
    path = ROOT / "prompts" / filename
    try:
        return path.read_text(encoding="utf-8").strip()
    except OSError:
        return ""

_PLACEHOLDER = "# generated by ralph"


# ── shared helpers ────────────────────────────────────────────────────────────

def _file_changed(path: Path) -> bool:
    """True if the file exists with content beyond the initial placeholder."""
    try:
        content = path.read_text(encoding="utf-8").strip()
        return bool(content) and content != _PLACEHOLDER
    except OSError:
        return False


def _git(repo_dir: Path, *args: str) -> subprocess.CompletedProcess:
    env = os.environ.copy()
    env.update(GIT_EDITOR="cmd /c exit 0", GIT_TERMINAL_PROMPT="0",
               PYTHONUTF8="1", PYTHONIOENCODING="utf-8")
    return subprocess.run(
        ["git", "-C", str(repo_dir), *args],
        capture_output=True, text=True, timeout=GIT_TIMEOUT, env=env,
    )


def commit_changes(repo_dir: Path, task: str, iteration: int) -> bool:
    """Stage and commit any file changes. Returns True if a commit was made."""
    status = _git(repo_dir, "status", "--porcelain")
    if not status.stdout.strip():
        return False
    _git(repo_dir, "add", "-A")
    r = _git(repo_dir, "commit", "-m", f"ralph iter {iteration}: {task[:70]}")
    return r.returncode == 0


def run_tests(repo_dir: Path) -> tuple[str, bool]:
    for cmd in (
        [sys.executable, "-m", "pytest", "test_solution.py", "--tb=short", "-q"],
        [sys.executable, "-m", "unittest", "test_solution.py", "-q"],
    ):
        span_id = tracer.start_tool("executor", "pytest", " ".join(cmd))
        result = subprocess.run(
            cmd, cwd=str(repo_dir), capture_output=True, text=True, timeout=60,
        )
        output = (result.stdout + result.stderr).strip()
        tracer.end_tool(span_id, "success" if result.returncode == 0 else "failed", output)
        if output:
            log_tool("pytest", f"CMD: {' '.join(cmd)}\n{output}")
            return output, result.returncode == 0
    return "(no tests found)", False


# ── local model path (direct Ollama API) ─────────────────────────────────────

_HEARTBEAT_EVERY = 15  # log a progress line every N seconds during generation
_CHUNK_TIMEOUT   = 30  # if Ollama sends no bytes for this long, treat as hung


def _wait_for_ollama(max_wait: int = 120) -> bool:
    """Block until Ollama is not busy, or max_wait seconds pass."""
    deadline = time.time() + max_wait
    payload = json.dumps({
        "model": "qwen25-coder-14b",
        "messages": [{"role": "user", "content": "hi"}],
        "stream": False
    }).encode("utf-8")
    
    log(f"  ollama | polling for idle state (max wait {max_wait}s)...")
    while time.time() < deadline:
        req = urllib.request.Request(
            f"{OLLAMA_API_BASE}/api/chat",
            data=payload,
            headers={"Content-Type": "application/json"},
        )
        try:
            with urllib.request.urlopen(req, timeout=5) as r:
                r.read()
            log("  ollama | server is now idle.")
            return True
        except (TimeoutError, urllib.error.URLError):
            pass
        except Exception:
            pass
        time.sleep(3)
    log("  ollama | WARN: gave up waiting for idle state.")
    return False


def _force_unload_ollama(model_name: str):
    """Force Ollama to unload the model and clear its queue."""
    log(f"  ollama | forcing keep_alive=0 unload for {model_name}...")
    try:
        payload = json.dumps({
            "model": model_name,
            "keep_alive": 0
        }).encode("utf-8")
        req = urllib.request.Request(
            f"{OLLAMA_API_BASE}/api/generate",
            data=payload,
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=3) as r:
            r.read()
    except Exception:
        pass


def _call_ollama(model_name: str, system: str, user: str,
                 budget: int = LOCAL_MODEL_TIMEOUT, num_ctx: int = 4096) -> str:
    """POST to Ollama /api/chat with streaming, return full response content.

    Budget check happens inside the streaming loop so that when we raise on
    timeout, the `with urlopen(...)` block closes the socket immediately —
    this terminates the Ollama HTTP request cleanly and frees the server for
    the next call. concurrent.futures-based timeouts don't close sockets;
    they leave the background thread (and the Ollama request) running.
    """
    payload = json.dumps({
        "model": model_name,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user",   "content": user},
        ],
        "stream": True,
        "options": {
            "temperature": 0, 
            "num_ctx": num_ctx,
            "stop": ["<|im_end|>", "<|endoftext|>", "```\n\n"]
        },
    }).encode("utf-8")
    req = urllib.request.Request(
        f"{OLLAMA_API_BASE}/api/chat",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    parts: list[str] = []
    chunk_count = 0
    t0 = time.time()
    last_heartbeat = t0
    with urllib.request.urlopen(req, timeout=_CHUNK_TIMEOUT) as r:
        for raw in iter(r.readline, b""):
            elapsed = time.time() - t0
            if elapsed > budget:
                raise TimeoutError(
                    f"local model generation exceeded {budget}s budget "
                    f"({chunk_count} tokens / {len(''.join(parts))} chars produced)"
                )
            if not raw.strip():
                continue
            try:
                chunk = json.loads(raw.decode("utf-8"))
            except json.JSONDecodeError:
                continue
            token = chunk.get("message", {}).get("content", "")
            if token:
                parts.append(token)
                chunk_count += 1
            now = time.time()
            if now - last_heartbeat >= _HEARTBEAT_EVERY:
                log(f"  ollama | generating... {now - t0:.0f}s elapsed, "
                    f"{chunk_count} tokens, {len(''.join(parts))} chars so far")
                last_heartbeat = now
            if chunk.get("done"):
                break
    return "".join(parts)


def _extract_code(response: str) -> str:
    """Pull the first ```python (or ```) block from the response."""
    for pattern in [r"```python\s*\n(.*?)```", r"```\s*\n(.*?)```"]:
        m = re.search(pattern, response, re.DOTALL)
        if m:
            return m.group(1).strip()
    # No fence found — strip prose and return whatever looks like code
    lines = [l for l in response.splitlines() if l.strip() and not l.startswith("#")]
    return "\n".join(lines).strip()


def _write_file_local(message: str, model: str, target: Path, label: str) -> tuple[str, str]:
    """Write a single file using the local model. Returns (response, error_or_empty)."""
    model_name = model.removeprefix("ollama/")
    
    # Capability Profiling
    free_vram = get_free_vram_mb()
    safe_ctx = calculate_safe_ctx(model_name, free_vram)
    profile = get_model_profile(model_name)
    system_prompt = load_prompt(profile.get("system_prompt", "local_system.txt"))
    
    log(f"local -> {label} model={model} timeout={LOCAL_MODEL_TIMEOUT}s ctx={safe_ctx} file={target.name}")
    t0 = time.time()
    flags = {
        "budget": LOCAL_MODEL_TIMEOUT,
        "num_ctx": safe_ctx,
        "temperature": 0
    }
    span_id = tracer.start_tool("executor", f"ollama [{model_name}]", message, flags=flags)

    try:
        response = _call_ollama(model_name, system_prompt, message, budget=LOCAL_MODEL_TIMEOUT, num_ctx=safe_ctx)
        tracer.end_tool(span_id, "success", response)
    except TimeoutError as e:
        tracer.end_tool(span_id, "failed", str(e))
        loud_timeout(f"local model {label} model={model}", LOCAL_MODEL_TIMEOUT, extra=str(e))
        _force_unload_ollama(model_name)
        return "", f"{TIMEOUT_SENTINEL} local model exceeded {LOCAL_MODEL_TIMEOUT}s"
    except Exception as e:
        tracer.end_tool(span_id, "failed", str(e))
        log(f"  local | {label} ERROR: {e}", also_console=True)
        return str(e), ""

    elapsed = time.time() - t0
    log(f"local <- {label} finished in {elapsed:.1f}s ({len(response)} chars)")

    # Log raw response for diagnosis
    log_tool("ollama", f"=== {label} ({elapsed:.1f}s) ===\nPROMPT:\n{message}\n\nRESPONSE:\n{response}")
    try:
        with open(AIDER_LOG_PATH, "a", encoding="utf-8", errors="replace") as f:
            f.write(f"\n=== {label} ({elapsed:.1f}s) ===\n{response}\n")
    except OSError:
        pass

    code = _extract_code(response)
    if not code:
        log(f"  local | {label} NO CODE BLOCK — raw response logged to {AIDER_LOG_PATH}",
            also_console=True)
        log(f"  local | Response preview: {response[:200]}", also_console=True)
        return response, ""

    target.write_text(code + "\n", encoding="utf-8")
    log(f"  local | {label} WRITTEN ({len(code.splitlines())} lines)")
    return response, ""


# ── cloud model path (Aider) ─────────────────────────────────────────────────

def _aider_env() -> dict:
    env = os.environ.copy()
    env.update(
        OLLAMA_API_BASE=OLLAMA_API_BASE,
        GIT_EDITOR="cmd /c exit 0",
        GIT_TERMINAL_PROMPT="0",
        PYTHONUTF8="1",
        PYTHONIOENCODING="utf-8",
    )
    return env


def _aider_cmd(message: str, model: str, target: Path) -> list[str]:
    return [
        sys.executable, "-m", "aider",
        "--yes",
        "--no-auto-commits",
        "--no-dirty-commits",
        "--no-auto-lint",
        "--no-show-model-warnings",
        "--model", model,
        "--message", message,
        str(target),
    ]


def _write_file_cloud(message: str, model: str, target: Path,
                      repo_dir: Path, label: str) -> tuple[str, str]:
    """Write a single file using Aider (cloud models). Returns (stdout, error_or_empty)."""
    log(f"aider -> {label} model={model} timeout={AIDER_TIMEOUT}s file={target.name}")
    cmd = _aider_cmd(message, model, target)
    flags = {
        "timeout": AIDER_TIMEOUT,
        "cmd": " ".join(cmd)
    }
    span_id = tracer.start_tool("executor", f"aider [{model}]", message, flags=flags)

    proc = subprocess.Popen(
        cmd, cwd=str(repo_dir),
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, encoding="utf-8", bufsize=1, env=_aider_env(),
    )

    captured: list[str] = []
    state = {"last_output": time.time(), "warned": False}

    def reader():
        try:
            for line in proc.stdout:
                state["last_output"] = time.time()
                captured.append(line)
                log(f"  aider | {line.rstrip()}", also_console=False)
        except Exception:
            pass

    rt = threading.Thread(target=reader, daemon=True)
    rt.start()

    deadline = time.time() + AIDER_TIMEOUT
    try:
        while proc.poll() is None:
            now = time.time()
            silence = now - state["last_output"]
            if not state["warned"] and silence >= SILENT_WARN_AFTER:
                state["warned"] = True
                log(f"  aider | WARN no output for {silence:.0f}s "
                    f"(hard timeout at {AIDER_TIMEOUT}s)")
            if now > deadline:
                loud_timeout(f"aider {label} model={model}", AIDER_TIMEOUT,
                             extra=f"silent for last {silence:.0f}s")
                try: proc.kill()
                except Exception: pass
                rt.join(timeout=2)
                tracer.end_tool(span_id, "failed", "".join(captured) + "\nTIMEOUT")
                return "".join(captured), f"{TIMEOUT_SENTINEL} aider exceeded {AIDER_TIMEOUT}s"
            time.sleep(0.5)
    except KeyboardInterrupt:
        log("aider | KeyboardInterrupt — killing subprocess")
        try: proc.kill()
        except Exception: pass
        rt.join(timeout=2)
        raise
    finally:
        state["running"] = False
        rt.join(timeout=2)

    rc = proc.returncode
    full_output = "".join(captured)
    tracer.end_tool(span_id, "success" if rc == 0 else "failed", full_output)
    
    log(f"aider <- {label} finished rc={rc}")
    try:
        with open(AIDER_LOG_PATH, "a", encoding="utf-8", errors="replace") as f:
            f.write(f"\n=== {label} ===\n{full_output}\n")
    except OSError:
        pass
    return full_output, "" if rc == 0 else f"aider exit {rc}"


# ── dispatcher ────────────────────────────────────────────────────────────────

def _write_file(message: str, model: str, target: Path,
                repo_dir: Path, label: str) -> tuple[str, str]:
    """Route to local or cloud writer based on model prefix."""
    if model.startswith("ollama/"):
        return _write_file_local(message, model, target, label)
    return _write_file_cloud(message, model, target, repo_dir, label)


# ── main entry point ──────────────────────────────────────────────────────────

def run_aider(task: str, plan: str, model: str, repo_dir: Path) -> tuple[str, str, str]:
    """Write solution.py then test_solution.py. One file per call.

    Returns (sol_output, test_output, sentinel_or_empty).
    """
    try:
        AIDER_LOG_PATH.write_text(
            f"=== RALPH run {__import__('datetime').datetime.now().isoformat(timespec='seconds')} ===\n",
            encoding="utf-8",
        )
    except OSError:
        pass

    solution  = repo_dir / "solution.py"
    test_file = repo_dir / "test_solution.py"
    if not solution.exists():
        solution.write_text(f"{_PLACEHOLDER}\n", encoding="utf-8")
    if not test_file.exists():
        test_file.write_text(f"{_PLACEHOLDER}\n", encoding="utf-8")

    plan_prefix = f"{plan}\n\n" if plan else ""
    sol_template = load_prompt("solution.txt")
    test_template = load_prompt("test_solution.txt")
    
    sol_prompt = sol_template.replace("{plan_prefix}", plan_prefix).replace("{task}", task)
    test_prompt = test_template.replace("{task}", task)

    sol_out, sol_err = _write_file(sol_prompt, model, solution, repo_dir, "solution.py")
    if sol_err.startswith(TIMEOUT_SENTINEL):
        return sol_out, "", sol_err

    sol_written = _file_changed(solution)
    log(f"  solution.py: {'WRITTEN' if sol_written else 'UNCHANGED'}")
    if not sol_written:
        log(f"  solution.py NO CODE — full output: {AIDER_LOG_PATH}", also_console=True)

    test_out, test_err = _write_file(test_prompt, model, test_file, repo_dir, "test_solution.py")
    if test_err.startswith(TIMEOUT_SENTINEL):
        return sol_out, test_out, test_err

    test_written = _file_changed(test_file)
    log(f"  test_solution.py: {'WRITTEN' if test_written else 'UNCHANGED'}")

    return sol_out, test_out, ""


def executor_node(state: RalphState) -> dict:
    model = select_model(state)
    repo_dir = Path(state["repo_dir"])
    iteration = state["iterations"] + 1

    if model.startswith("ollama/"):
        log("  ollama | cooldown (2s) to prevent HTTP 500...")
        time.sleep(2)

    task_prompt = state["task"]
    # State Routing Matrix: Dynamic Prompt Injection for Timeouts
    if state.get("timeout_count", 0) > 0 and model.startswith("ollama/"):
        task_prompt = "CRITICAL WARNING: Your previous generation timed out (likely infinite loop). Provide ONLY the raw code. Do not explain anything.\n\n" + task_prompt

    sol_out, test_out, stderr = run_aider(task_prompt, state.get("plan", ""), model, repo_dir)

    if stderr.startswith(TIMEOUT_SENTINEL):
        if model.startswith("ollama/"):
            _wait_for_ollama()
        return {
            "code": "",
            "test_output": TIMEOUT_SENTINEL,
            "model_used": model,
            "iterations": iteration,
            "timeout_count": state.get("timeout_count", 0) + 1,
            "log": state["log"] + [f"[iter {iteration}] executor -> model={model} | TIMEOUT"],
        }

    solution = repo_dir / "solution.py"
    code = solution.read_text(encoding="utf-8") if solution.exists() else ""
    edit_applied = _file_changed(solution)

    committed = commit_changes(repo_dir, state["task"], iteration) if edit_applied else False
    test_output, _ = run_tests(repo_dir)

    log_entry = (
        f"[iter {iteration}] executor -> model={model} | "
        f"{'edit applied' if edit_applied else 'no edit'}"
        f"{' | committed' if committed else ''}"
    )
    return {
        "code": code,
        "test_output": test_output,
        "model_used": model,
        "iterations": iteration,
        "timeout_count": 0,
        "log": state["log"] + [log_entry],
    }
