"""D6: Full RALPH loop smoke test.
Creates a fresh isolated temp repo, runs one planner -> executor -> evaluator
iteration with the simplest possible task, verifies solution.py was written.
This is the integration test — all prior D1-D5 must pass first.
"""
import sys, os, subprocess, tempfile, shutil
sys.path.insert(0, str(__import__("pathlib").Path(__file__).parent.parent))
import config

PYTHON = sys.executable
RALPH_DIR = str(__import__("pathlib").Path(__file__).parent.parent)

def check(label, fn):
    try:
        result = fn()
        print(f"  PASS  {label}")
        return True, result
    except Exception as e:
        print(f"  FAIL  {label}")
        print(f"        {type(e).__name__}: {e}")
        return False, None

def graph_imports():
    from graph import build_graph  # noqa: F401

def loop_writes_solution():
    tmp = tempfile.mkdtemp(prefix="ralph_d6_")
    try:
        # bare git repo for the target
        subprocess.run(["git", "init", tmp], check=True, capture_output=True)
        subprocess.run(["git", "-C", tmp, "config", "user.email", "test@ralph"], capture_output=True)
        subprocess.run(["git", "-C", tmp, "config", "user.name", "ralph-test"], capture_output=True)
        with open(os.path.join(tmp, "README.md"), "w") as f:
            f.write("# test target\n")
        subprocess.run(["git", "-C", tmp, "add", "."], capture_output=True)
        subprocess.run(["git", "-C", tmp, "commit", "-m", "init"], capture_output=True)

        result = subprocess.run(
            [PYTHON, "main.py", "--repo", tmp,
             "write a Python function called add that adds two numbers"],
            cwd=RALPH_DIR,
            capture_output=True, text=True, timeout=360,
        )
        combined = result.stdout + result.stderr
        solution = os.path.join(tmp, "solution.py")
        assert os.path.exists(solution), (
            f"solution.py not created.\n"
            f"--- stdout (last 1000) ---\n{result.stdout[-1000:]}\n"
            f"--- stderr (last 500) ---\n{result.stderr[-500:]}"
        )
        content = open(solution).read()
        assert content.strip() and content.strip() != "# generated by ralph", (
            f"solution.py is empty / placeholder:\n{content}"
        )
        print(f"          solution.py written ({len(content.splitlines())} lines)")
        print(f"          preview: {content.strip()[:120]!r}")
        return content
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

if __name__ == "__main__":
    print(f"\n[D6] RALPH full loop  (using {RALPH_DIR})")
    print(f"     NOTE: this runs Aider against a temp repo — takes 1-3 minutes\n")
    r1, _ = check("graph.py imports cleanly", graph_imports)
    r2, _ = check("loop writes solution.py in temp repo", loop_writes_solution)
    ok = r1 and r2
    print(f"\n  {'ALL PASS' if ok else 'FAILED'}\n")
    sys.exit(0 if ok else 1)
