<#
.SYNOPSIS
    Reset a Task Pod to a clean state for a fresh RALPH run.

.DESCRIPTION
    Resets solution.py to the placeholder sentinel, clears checkpoints,
    traces, and aider logs. The task spec (test_solution.py), topology,
    and task.json are never touched.

.PARAMETER TaskName
    Name of the task directory under tasks/ (e.g. 001_fibonacci).
    If omitted, lists available task pods and exits.

.EXAMPLE
    pwsh -File scripts\reset-task.ps1 001_fibonacci
#>
param(
    [string]$TaskName
)

$ralphRoot = Split-Path -Parent $PSScriptRoot
$tasksDir  = Join-Path $ralphRoot 'tasks'
$placeholder = '# generated by ralph'

# No argument — list available pods and exit
if (-not $TaskName) {
    Write-Host "Available task pods:"
    Get-ChildItem $tasksDir -Directory | ForEach-Object { Write-Host "  $($_.Name)" }
    Write-Host "`nUsage: pwsh -File scripts\reset-task.ps1 <task-name>"
    exit 0
}

$taskDir = Join-Path $tasksDir $TaskName
if (-not (Test-Path $taskDir)) {
    Write-Error "Task pod not found: $taskDir"
    exit 1
}

Write-Host "Resetting task pod: $TaskName"

# 1. Reset solution.py — never reset test_solution.py (it is the spec)
$solutionPath = Join-Path $taskDir 'src\solution.py'
if (Test-Path $solutionPath) {
    Set-Content -Path $solutionPath -Value $placeholder
    Write-Host "  [reset] src/solution.py"
} else {
    Write-Host "  [skip]  src/solution.py not found"
}

# 2. Delete checkpoints (LangGraph SQLite state)
$checkpointsPath = Join-Path $taskDir 'checkpoints.sqlite'
if (Test-Path $checkpointsPath) {
    Remove-Item $checkpointsPath -Force
    Write-Host "  [del]   checkpoints.sqlite"
}

# 3. Delete traces directory
$tracesPath = Join-Path $taskDir 'traces'
if (Test-Path $tracesPath) {
    Remove-Item $tracesPath -Recurse -Force
    Write-Host "  [del]   traces/"
}

# 4. Delete aider log from src/
$aiderLog = Join-Path $taskDir 'src\aider_last.log'
if (Test-Path $aiderLog) {
    Remove-Item $aiderLog -Force
    Write-Host "  [del]   src/aider_last.log"
}

# 5. Delete run console/crash logs if present
foreach ($logFile in @('run_console.log', 'CRASH.log')) {
    $logPath = Join-Path $taskDir $logFile
    if (Test-Path $logPath) {
        Remove-Item $logPath -Force
        Write-Host "  [del]   $logFile"
    }
}

Write-Host "`nDone. Run with:"
Write-Host "  python src/main.py run tasks/$TaskName/"
